backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "lotstatus"
    label: "Lot Status Upload"
    files:
      - file: "data/dummy.md"
        label: "Upload JSON"
        name: "lot_upload"
        fields:
          - name: "upload"
            label: "JSON File"
            widget: "file"
            media_library:
              config:
                multiple: false
