backend:
  name: git-gateway
  branch: main

media_folder: ""
public_folder: ""

collections:
  - name: "lotstatus"
    label: "Lot Status"
    files:
      - file: "data/lotstatus/lot-status.json"
        label: "Upload Lot Status JSON"
        name: "lotstatus"
        fields:
          - label: "Upload JSON file"
            name: "jsonfile"
            widget: "file"
            media_folder: "data/lotstatus"
            public_folder: "/data/lotstatus"
