backend:
  name: git-gateway
  branch: main

media_folder: ""
public_folder: ""

collections:
  - name: "lotstatus"
    label: "Lot Status JSON"
    files:
      - file: "lot-status.json"
        label: "Lot Status File"
        name: "lotstatusfile"
        fields:
          - label: "Raw JSON"
            name: "lots"
            widget: "text"
            default: '{ "lots": [] }'
