backend:
  name: github
  repo: andresmtzc/arquidromoWeb
  branch: main
  auth_scope: repo
  base_url: https://auth.netlify.com  # required for OAuth with GitHub Pages


media_folder: ""
public_folder: ""

collections:
  - name: "lotstatus"
    label: "Lot Status"
    files:
      - file: "lot-status.json"
        label: "Lot Data"
        name: "lots"
        editor:
          preview: false
