backend:
  name: git-gateway
  branch: main  # or your default branch

media_folder: ""
public_folder: ""

collections:
  - name: "lotstatus"
    label: "Lot Status"
    files:
      - file: "lot-status.json"
        label: "Lot Data"
        name: "lots"
        editor:
          preview: false
        fields:
          - label: "Lot List"
            name: "lots"
            widget: list
            summary: "Lot {{fields.id}} - {{fields.status}}"
            fields:
              - { label: "ID", name: "id", widget: number }
              - { label: "Status", name: "status", widget: select, options: ["available", "sold", "unavail"] }
