backend:
  name: git-gateway
  branch: main

media_folder: ""
public_folder: ""

collections:
  - name: "lotstatus"
    label: "Lot Status"
    folder: "data/lotstatus"
    format: json
    extension: "json"
    create: false
    delete: false
    editor:
      preview: false
    fields:
      - label: "Raw JSON"
        name: "json"
        widget: code
        output_code_only: true
        code_mirror:
          mode: application/json
