backend:
  name: github
  repo: andresmtzc/arquidromoWeb
  branch: main  # or 'master' depending on your default branch

media_folder: ""
public_folder: ""

collections:
  - name: "lotstatus"
    label: "Lot Status"
    files:
      - file: "lot-status.json"
        label: "Lot Data"
        name: "lots"
        editor:
          preview: false
