backend:
  name: git-gateway
  branch: main

media_folder: ""
public_folder: ""

collections:
  - name: "lotstatus"
    label: "Lot Status"
    files:
      - file: "lot-status.json"
        label: "Lot Status JSON"
        name: "lotstatus"
        format: json
        single_file: true
        editor:
          preview: false
        widget: code
        code_mirror:
          mode: "application/json"
