backend:
  name: git-gateway
  branch: main

media_folder: ""
public_folder: ""

collections:
  - name: "lotstatus"
    label: "Lot Status"
    files:
      - file: "data/lotstatus/lot-status.json"
        label: "Lot Status JSON"
        name: "lotstatus"
        editor:
          preview: false
        fields:
          - name: "body"
            label: "Raw JSON"
            widget: "text"
            multiline: true
            raw: true
