backend:
  name: git-gateway
  branch: main

media_folder: ""
public_folder: ""

collections:
  - name: "lotstatus"
    label: "Lot Status"
    files:
      - file: "lot-status.json"
        label: "Lot Status JSON"
        name: "lots"
        editor:
          preview: false
        fields:
          - label: "Raw JSON"
            name: "body"
            widget: code
            output_code_only: true
            code_mirror:
              mode: "application/json"
