name: Update Lot Manifest from dummy.md

on:
  push:
    branches:
      - main
    paths:
      - 'data/dummy.md'

jobs:
  update-manifest:
    if: contains(github.event.head_commit.message, 'Lot Status Upload')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Read latest uploaded filename from dummy.md
        id: read_filename
        run: |
          # Extract the line starting with /uploads/ (assuming that line contains the path)
          filepath=$(grep '^/uploads/' data/dummy.md | head -n1)
          echo "filepath=$filepath" >> "$GITHUB_OUTPUT"

      - name: Ensure public/data directory exists
        run: mkdir -p public/data

      - name: Update lot-manifest.json using dummy.md filename
        run: |
          echo "{ \"file\": \"$filepath\" }" > public/data/lot-manifest.json

      - name: Commit and push updated lot-manifest.json
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add public/data/lot-manifest.json
          git commit -m "Update lot-manifest.json from dummy.md"
          git push
