name: Update lot-manifest.json from dummy.md

on:
  push:
    branches:
      - main
    paths:
      - 'data/dummy.md'

jobs:
  update-manifest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Extract uploaded JSON filename from dummy.md
        id: extract
        run: |
          FILE_LINE=$(grep '^upload:' data/dummy.md || true)
          echo "Found line: $FILE_LINE"
          FILE_PATH=$(echo "$FILE_LINE" | sed 's/upload:[ ]*//' | xargs)
          FILE_NAME=$(basename "$FILE_PATH")
          echo "filename=$FILE_NAME" >> $GITHUB_OUTPUT

      - name: Fail if no filename found
        if: steps.extract.outputs.filename == ''
        run: |
          echo "No uploaded filename found in dummy.md"
          exit 1

      - name: Write lot-manifest.json
        run: |
          echo "{\"latest\": \"${{ steps.extract.outputs.filename }}\"}" > public/uploads/lot-manifest.json

      - name: Commit and push lot-manifest.json
        run: |
          git config user.name "Netlify CMS Bot"
          git config user.email "cms-bot@example.com"
          git add public/uploads/lot-manifest.json
          git commit -m "Update lot-manifest.json to ${{ steps.extract.outputs.filename }}"
          git push
